version: 0.2

env:
  variables:
    IMAGE_NAME: simple-python-app
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /myapp/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /myapp/docker-credentials/password
    DOCKER_REGISTRY_URL: /myapp/docker-registry/url

phases:
  pre_build:
    commands:
      - echo "Logging into DockerHub"
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker image"
      - docker build -t $DOCKER_REGISTRY_USERNAME/$IMAGE_NAME:latest .

  post_build:
    commands:
      - echo "Pushing image to DockerHub"
      - docker push $DOCKER_REGISTRY_USERNAME/$IMAGE_NAME:latest
